"""jobs categories

Revision ID: 7b40e3f1b909
Revises: cf06ec0acee5
Create Date: 2021-03-07 20:29:11.373816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b40e3f1b909'
down_revision = 'cf06ec0acee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('jobs', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'job_category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'category_id')
    op.drop_table('job_category')
    # ### end Alembic commands ###
