"""city_from param to User attempt2

Revision ID: 8a8a5fa48aed
Revises: 2e0cc5669ef4
Create Date: 2021-03-13 00:52:17.511009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a8a5fa48aed'
down_revision = '2e0cc5669ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_from', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('city_from')

    # ### end Alembic commands ###
